### ISSUE TITLE
Empty "in:" in Trace and Warn with happyDevFormatter

### ISSUE THREAD

**Issue by mwmahlberg** [mgutz/logxi#21]
When calling `Warn()` or  `Trace()` only with a string, the happyDevFormatter prints an empty "in:" at the end of the line.

The [according code in the happyDeFormatter.go](https://github.com/mgutz/logxi/blob/master/v1/happyDevFormatter.go#L351) does not seem to trigger.

**Comment by mgutz** [comment]
Should have a fix in the next couple of days. The stack format changed in 1.6. Just so I have notes when I work on this:

go 1.5

```go
/usr/src/myapp/main.go:9 (0x401024)
	main: fmt.Println(string(debug.Stack()))
/usr/local/go/src/runtime/proc.go:111 (0x429190)
	main: main_main()
/usr/local/go/src/runtime/asm_amd64.s:1721 (0x455a11)
	goexit: BYTE	$0x90	// NOP
```

go 1.6

```go
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
main.main()
	/usr/src/myapp/main.go:9 +0x24
```

**Comment by huangyingyi** [comment]
Is this fixed yet?

**Comment by AlbinoGeek** [comment]
Nope, still not fixed.

**Comment by coopernurse** [comment]
@AlbinoGeek I see you have a more active fork of this project. Would you be open to receiving patches on your fork and perhaps cutting some release tags periodically?

If so I'll put a note on #47 about that.

**Comment by AlbinoGeek** [comment]
Sounds good. I use this package in all my projects, it's probably time to give back, haha.
